

CREATE TABLE BOOK (
  id VARCHAR(250) PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  details VARCHAR(250) NOT NULL,
  price DOUBLE,
  image VARCHAR(250) NOT NULL,
  viewVector VARCHAR(250) NOT NULL
);


CREATE TABLE BOOKS_VIEW (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  bookId VARCHAR(250) NOT NULL,
  userId VARCHAR(250) NOT NULL
);


CREATE TABLE USERS (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  userId VARCHAR(250) NOT NULL
)
